language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t dipakrchavda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dipakrchavda/docker-react npm run test
